### ISSUE TITLE
Creating new DB fails

### ISSUE THREAD

**Issue by jkiviluo** [spine-tools/Spine-Toolbox#2337]
When trying to create a new sqlite DB in v0.8 latest, it fails with:

```
Traceback (most recent call last):
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\ui_main.py", line 695, in save_project
    self._project.save()
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\project.py", line 207, in save
    "connections": [connection.to_dict() for connection in self._connections],
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\project.py", line 207, in <listcomp>
    "connections": [connection.to_dict() for connection in self._connections],
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\project_item\logging_connection.py", line 382, in to_dict
    if self.has_filters():
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\project_item\logging_connection.py", line 161, in has_filters
    db_map = self._get_db_map(url, ignore_version_error=True)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\project_item\logging_connection.py", line 174, in _get_db_map
    db_map = self._toolbox.db_mngr.get_db_map(url, self._toolbox, ignore_version_error=ignore_version_error)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 330, in get_db_map
    return self._do_get_db_map(url, codename, create, upgrade)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\helpers.py", line 122, in new_function
    return func(*args, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 385, in _do_get_db_map
    raise error
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_manager.py", line 382, in _do_get_db_map
    db_map = worker.get_db_map(codename=codename, upgrade=upgrade, create=create)
  File "C:\data\spi-entity\Spine-Toolbox\spinetoolbox\spine_db_worker.py", line 53, in get_db_map
    self._db_map = DatabaseMapping(self._db_url, *args, sqlite_timeout=2, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\data\spi-entity\Spine-Toolbox\src\spinedb-api\spinedb_api\db_mapping_base.py", line 108, in __init__
    self._original_engine = self._create_engine(
AttributeError: 'DatabaseMapping' object has no attribute '_create_engine'
```

**Comment by soininen** [comment]
Have you checked out `0.8-dev` branch in *all* Spine repositories including Spine-Database-API?

**Comment by manuelma** [comment]
It was my fault, it's now fixed in latest spinedb_api 0.8-dev. Sorry!

**Comment by jkiviluo** [comment]
I'm reopening, since the fix didn't work for me. Still the same error.

**Comment by jkiviluo** [comment]
Works now after the latest commits.
