### ISSUE TITLE
Changing data store path (in Data Store Properties) creates empty file for each edited letter

### ISSUE THREAD

**Issue by eriharriso** [spine-tools/Spine-Toolbox#2930]
**What I was doing:** changed the path to my sqlite Data Store in the Data Store Properties URL menu ("Database:" text box). Specifically, I changed the name of the data store from "ines-spec" to "ines-spec_only_structure".

![image](https://github.com/user-attachments/assets/553b8b36-7828-4119-8265-c9eee26be28c)

**What happened:** empty sqlite files were created in the same folder for each letter I added to the new name (see figure).

![image](https://github.com/user-attachments/assets/9342db43-bd3f-4609-8423-73db0e45df4c)

**What I expected:** for Toolbox to simply look for the data store in the specified path without creating any extra files.

**Version:** installed from source in Sep 10 2024.

**Comment by ptsavol** [comment]
@eriharriso Should be fixed now.

**Comment by soininen** [comment]
You still get an empty file when you finish editing if the database points to a non-existing path. I think the real culprit here could be `_ValidationTask.run()` or someplace else where we call `check_database_url()` before properly checking if the SQLite file exists (note that other, non-file based databases do not have files).

Also, please revert the `textChanged` -> `editingFinished` change. Using the `editingFinished` signal to track changes in LineEdits forces users to press Enter or accept their edit in some other way to apply the changes which just does not feel natural. Wiring the updates to `textChanged` makes the UI more fluid.

**Comment by ptsavol** [comment]
'The fix' has been reverted.
